export const CAPABILITIES = {
  MANAGE_LPN: "MANAGE_LPN",
  MANAGE_GENERAL_ACTIVITIES: "MANAGE_GENERAL_ACTIVITIES",
  MANAGE_GRADEBOOK: "MANAGE_GRADEBOOK",
  MANAGE_COURSE_DATES: "MANAGE_COURSE_DATES",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_HOMEWORK_ACTIVITIES: "MANAGE_HOMEWORK_ACTIVITIES",
  ALL: "*",
} as const;

export type Capabilities = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];
