export const MODAL_TYPES = {
  ABOUT: "ABOUT",
  NODE_INFO: "NODE_INFO",
  IDLE_MODAL: "IDLE_MODAL",
  UNARCHIVE: "UNARCHIVE",
  MOVE_ACTIVITY: "MOVE_ACTIVITY",
  BULK_EDIT_DATES: "BULK_EDIT_DATES",
  COURSE_SCHEDULE_TEMPLATE: "COURSE_SCHEDULE_TEMPLATE",
  AUTO_SET_POINTS_POSSIBLE: "AUTO_SET_POINTS_POSSIBLE",
} as const;
export type ModalTypes = (typeof MODAL_TYPES)[keyof typeof MODAL_TYPES];
