export const NODE_VIEWS = {
  STUDENT_EMPTY_CONTAINER: "STUDENT_EMPTY_CONTAINER",
  EMPTY_CONTAINER: "EMPTY_CONTAINER",
  EMPTY_BY_HIDDEN_NODES: "EMPTY_BY_HIDDEN_NODES",
  EMPTY_BY_FILTER: "EMPTY_BY_FILTER",
  TOPIC_CONTENT: "TOPIC_CONTENT",
};
export type NodeView = (typeof NODE_VIEWS)[keyof typeof NODE_VIEWS];
