export const NOTEBOOK_LM_COURSE_STATUS = {
  DISABLED: "DISABLED",
  ENABLED: "ENABLED",
  NOT_SUPPORTED: "NOT_SUPPORTED",
  NOT_INITIALIZED: "NOT_INITIALIZED",
} as const;
export type NotebookLMCourseStatus =
  (typeof NOTEBOOK_LM_COURSE_STATUS)[keyof typeof NOTEBOOK_LM_COURSE_STATUS];
