export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  INSTRUCTOR: "INSTRUCTOR",
  STUDENT: "STUDENT",
  PRODUCTION: "PRODUCTION",
  VENDOR: "VENDOR",
  EDITOR: "EDITOR",
  COURSECARE: "COURSECARE",
  REVIEWER: "REVIEWER",
  TEACHING_ASSISTANT: "TEACHING_ASSISTANT",
} as const;
export type Roles = (typeof ROLES)[keyof typeof ROLES];

export const ADMIN_LIKE_ROLES: Roles[] = [
  ROLES.SUPER_ADMIN,
  ROLES.PRODUCTION,
  ROLES.VENDOR,
  ROLES.EDITOR,
  ROLES.COURSECARE,
  ROLES.REVIEWER,
];

export const CAN_MANAGE_LPN_ROLES: Roles[] = [
  ROLES.SUPER_ADMIN,
  ROLES.PRODUCTION,
  ROLES.VENDOR,
];

export const CAN_REMOVE_ALL_ACTIVITIES: Roles[] = [
  ROLES.SUPER_ADMIN,
  ROLES.COURSECARE,
];

export const INSTRUCTOR_LIKE_ROLES: Roles[] = [
  ROLES.INSTRUCTOR,
  ROLES.TEACHING_ASSISTANT,
];

export const SUPPORTED_APP_DOCK_DRAGGABLE_ROLES: Roles[] = [
  ROLES.INSTRUCTOR,
  ROLES.COURSECARE,
  ROLES.SUPER_ADMIN,
  ROLES.TEACHING_ASSISTANT,
];
